### ISSUE TITLE
Add support for Laravel 5.7

### ISSUE THREAD

**Issue by worldpac** [michielfb/laravel-data-migration#6]
This version of the repository is not compatible with Laravel 5.7.

The Laravel [Migrator](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Database/Migrations/Migrator.php) has changed slightly and outputs notes automatically as it runs. There is no longer a `getNotes()` function, or need for the `foreach()` loop at the end of the `handle()` function in [MigrateData.php](https://github.com/michielfb/laravel-data-migration/blob/master/src/Console/Commands/RollbackMigrateData.php#L61) or [RollbackMigrateData.php](https://github.com/michielfb/laravel-data-migration/blob/master/src/Console/Commands/RollbackMigrateData.php#L61).

I've already forked your repo and fixed it for us, but if you'd like I can submit a pull request.

John

**Comment by michielfb** [comment]
Hi @worldpac , a pull request would be very much appreciated.

**Comment by worldpac** [comment]
I think I did that right. If not, let me know.

https://github.com/michielfb/laravel-data-migration/pull/7

**Comment by worldpac** [comment]
I was just thinking that the change in the PR would not be backwards compatible. It works for us, as we are moving to 5.7, but probably wouldn't work for your repo if you want to maintain compatibility with previous versions of Laravel, such as 5.5.

**Comment by michielfb** [comment]
I don't think I've ever used the option to add a note. I've bumped the major version just in case. Fixed in 1.0.0.
